CREATE DATABASE QUANLYVATNUOICAYTRONG
GO
USE QUANLYVATNUOICAYTRONG
GO
CREATE TABLE DOI_TUONG
(
	IDDOITUONG CHAR(5),
	TENDOITUONG NVARCHAR(20),
	IDKHUVUC CHAR(5),
	NGAYNHAP DATE,
	NGAYXUAT DATE,
	CONSTRAINT PK_DOITUONG
	PRIMARY KEY (IDDOITUONG)
)
GO
CREATE TABLE LOAI_THUCAN_PHANBON
(
	IDLOAI CHAR(5),
	TENLOAI NVARCHAR(20),
	CONSTRAINT PK_LOAITHUCANPHANBON
	PRIMARY KEY (IDLOAI)
)
GO
CREATE TABLE LUONG_TIEU_THU
(
	IDDOITUONG CHAR(5),
	IDLOAI CHAR(5),
	SOLUONG_1NGAY INT,
	CONSTRAINT PK_LUONGTIEUTHU
	PRIMARY KEY (IDDOITUONG,IDLOAI)
)
GO
CREATE TABLE KHU_VUC
(
	IDKHUVUC CHAR(5) PRIMARY KEY,
	TENKHUVUC NVARCHAR(20),
)
GO
CREATE TABLE NHA_CUNG_CAP
(
	IDNCC CHAR(5),
	TENNCC NVARCHAR(20),
	TENSPCUNGCAP NVARCHAR(20),
	DIACHI NVARCHAR(100),
	SDT CHAR(11),
	CONSTRAINT PK_NCC
	PRIMARY KEY(IDNCC)
)
GO
CREATE TABLE CHI_PHI_THUC_PHAN
(
	IDLOAI CHAR(5),
	IDNCC CHAR(5),
	SOLUONG INT,
	GIA_1KG INT,
	CONSTRAINT PK_CHIPHITHUCPHAN
	PRIMARY KEY(IDLOAI,IDNCC)
)
GO
CREATE TABLE CHI_PHI_DOI_TUONG
(
	IDDOITUONG CHAR(5),
	IDNCC CHAR(5),
	SOLUONG INT,
	GIA_1CON INT,
	CONSTRAINT PK_CHIPHIDOITUONG
	PRIMARY KEY(IDDOITUONG,IDNCC)
)
GO
CREATE TABLE BENH
(
	IDBENH CHAR(5),
	TENBENH NVARCHAR(50),
	DAUHIEU NVARCHAR(100),
	CONSTRAINT PK_BENH
	PRIMARY KEY (IDBENH)
)
GO
CREATE TABLE TINH_TRANG_SUC_KHOE
(
	IDDOITUONG CHAR(5),
	IDBENH CHAR(5),
	TINHTRANG NVARCHAR(20),
	CHIPHICHUATRI INT,
	CONSTRAINT PK_TINHTRANGSUCKHOE
	PRIMARY KEY(IDDOITUONG,IDBENH)
)
GO
CREATE TABLE NGUON_TIEU_THU
(
	IDNHATIEUTHU CHAR(5),
	TENNHATIEUTHU NVARCHAR(20),
	SPTHUMUA NVARCHAR(20),
	DIACHI NVARCHAR(100),
	SDT CHAR(11),
	CONSTRAINT PK_NGUONTIEUTHU
	PRIMARY KEY (IDNHATIEUTHU)
	
)
GO
CREATE TABLE THU
(
	IDDOITUONG CHAR(5),
	IDNHATIEUTHU CHAR(5),
	IDSANPHAMTIEUTHU CHAR(5),
	TENSANPHAMTIEUTHU NVARCHAR(50),
	SOLUONG INT,
	GIATHANH INT,
	CONSTRAINT PK_THU
	PRIMARY KEY (IDDOITUONG,IDNHATIEUTHU,IDSANPHAMTIEUTHU)
)
--FK
--DOITUONG
ALTER TABLE dbo.DOI_TUONG
ADD CONSTRAINT FK_DT_KV
FOREIGN KEY (IDKHUVUC)
REFERENCES dbo.KHU_VUC(IDKHUVUC)
GO
--LUONGTIEUTHU
ALTER TABLE dbo.LUONG_TIEU_THU
ADD CONSTRAINT FK_LTT_DT
FOREIGN KEY (IDDOITUONG)
REFERENCES dbo.DOI_TUONG(IDDOITUONG)
GO
ALTER TABLE dbo.LUONG_TIEU_THU
ADD CONSTRAINT FK_LTT_LOAI
FOREIGN KEY (IDLOAI)
REFERENCES dbo.LOAI_THUCAN_PHANBON(IDLOAI)
GO
--CHIPHITHUCAN_PB
ALTER TABLE dbo.CHI_PHI_THUC_PHAN
ADD CONSTRAINT FK_CPTAPB_LOAI
FOREIGN KEY(IDLOAI)
REFERENCES dbo.LOAI_THUCAN_PHANBON(IDLOAI)
GO
ALTER TABLE dbo.CHI_PHI_THUC_PHAN
ADD CONSTRAINT FK_CPTAPB_NCC
FOREIGN KEY(IDNCC)
REFERENCES dbo.NHA_CUNG_CAP(IDNCC)
GO
--CHIPHI_DOITUONG
ALTER TABLE dbo.CHI_PHI_DOI_TUONG
ADD CONSTRAINT FK_CPDT_DT
FOREIGN KEY (IDDOITUONG)
REFERENCES dbo.DOI_TUONG(IDDOITUONG)
GO
ALTER TABLE dbo.CHI_PHI_DOI_TUONG
ADD CONSTRAINT FK_CPDT_NCC
FOREIGN KEY(IDNCC)
REFERENCES dbo.NHA_CUNG_CAP(IDNCC)
GO
--TINHTRANG_SUCKHOE
ALTER TABLE dbo.TINH_TRANG_SUC_KHOE
ADD CONSTRAINT FK_TTSK_DT
FOREIGN KEY (IDDOITUONG)
REFERENCES dbo.DOI_TUONG(IDDOITUONG)
GO
ALTER TABLE dbo.TINH_TRANG_SUC_KHOE
ADD CONSTRAINT FK_TTSK_BENH
FOREIGN KEY (IDBENH)
REFERENCES dbo.BENH(IDBENH)
GO
--THU
ALTER TABLE dbo.THU
ADD CONSTRAINT FK_THU_DT
FOREIGN KEY (IDDOITUONG)
REFERENCES dbo.DOI_TUONG(IDDOITUONG)
GO
ALTER TABLE dbo.THU
ADD CONSTRAINT FK_THU_TT
FOREIGN KEY (IDNHATIEUTHU)
REFERENCES dbo.NGUON_TIEU_THU(IDNHATIEUTHU)