//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class BENH
    {
        public BENH()
        {
            this.TINH_TRANG_SUC_KHOE = new HashSet<TINH_TRANG_SUC_KHOE>();
        }
    
        public string IDBENH { get; set; }
        public string TENBENH { get; set; }
        public string DAUHIEU { get; set; }
        public string PHONGBENH { get; set; }
    
        public virtual ICollection<TINH_TRANG_SUC_KHOE> TINH_TRANG_SUC_KHOE { get; set; }
    }
}
