//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_PHI_THUC_PHAN
    {
        public string IDLOAI { get; set; }
        public string IDNCC { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<int> GIA_1KG { get; set; }
    
        public virtual LOAI_THUCAN_PHANBON LOAI_THUCAN_PHANBON { get; set; }
        public virtual NHA_CUNG_CAP NHA_CUNG_CAP { get; set; }
    }
}
