//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_PHI_DOI_TUONG
    {
        public int IDDOITUONG { get; set; }
        public string IDNCC { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<int> GIA_1CON { get; set; }
    
        public virtual DOI_TUONG DOI_TUONG { get; set; }
        public virtual NHA_CUNG_CAP NHA_CUNG_CAP { get; set; }
    }
}
