//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOI_TUONG
    {
        public DOI_TUONG()
        {
            this.CHI_PHI_DOI_TUONG = new HashSet<CHI_PHI_DOI_TUONG>();
            this.LUONG_TIEU_THU = new HashSet<LUONG_TIEU_THU>();
            this.TINH_TRANG_SUC_KHOE = new HashSet<TINH_TRANG_SUC_KHOE>();
            this.THU = new HashSet<THU>();
        }
    
        public int IDDOITUONG { get; set; }
        public string TENDOITUONG { get; set; }
        public string IDKHUVUC { get; set; }
        public string IDLOAIDOITUONG { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
        public Nullable<System.DateTime> NGAYXUAT { get; set; }
    
        public virtual ICollection<CHI_PHI_DOI_TUONG> CHI_PHI_DOI_TUONG { get; set; }
        public virtual KHU_VUC KHU_VUC { get; set; }
        public virtual LOAI_DOI_TUONG LOAI_DOI_TUONG { get; set; }
        public virtual ICollection<LUONG_TIEU_THU> LUONG_TIEU_THU { get; set; }
        public virtual ICollection<TINH_TRANG_SUC_KHOE> TINH_TRANG_SUC_KHOE { get; set; }
        public virtual ICollection<THU> THU { get; set; }
    }
}
