//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAI_THUCAN_PHANBON
    {
        public LOAI_THUCAN_PHANBON()
        {
            this.CHI_PHI_THUC_PHAN = new HashSet<CHI_PHI_THUC_PHAN>();
            this.LUONG_TIEU_THU = new HashSet<LUONG_TIEU_THU>();
        }
    
        public string IDLOAI { get; set; }
        public string TENLOAI { get; set; }
    
        public virtual ICollection<CHI_PHI_THUC_PHAN> CHI_PHI_THUC_PHAN { get; set; }
        public virtual ICollection<LUONG_TIEU_THU> LUONG_TIEU_THU { get; set; }
    }
}
