//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManage
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QUANLYVATNUOICAYTRONGEntities : DbContext
    {
        public QUANLYVATNUOICAYTRONGEntities()
            : base("name=QUANLYVATNUOICAYTRONGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BENH> BENH { get; set; }
        public DbSet<CHI_PHI_DOI_TUONG> CHI_PHI_DOI_TUONG { get; set; }
        public DbSet<CHI_PHI_THUC_PHAN> CHI_PHI_THUC_PHAN { get; set; }
        public DbSet<DOI_TUONG> DOI_TUONG { get; set; }
        public DbSet<KHU_VUC> KHU_VUC { get; set; }
        public DbSet<LOAI_DOI_TUONG> LOAI_DOI_TUONG { get; set; }
        public DbSet<LOAI_THUCAN_PHANBON> LOAI_THUCAN_PHANBON { get; set; }
        public DbSet<LUONG_TIEU_THU> LUONG_TIEU_THU { get; set; }
        public DbSet<NGUON_TIEU_THU> NGUON_TIEU_THU { get; set; }
        public DbSet<NHA_CUNG_CAP> NHA_CUNG_CAP { get; set; }
        public DbSet<TINH_TRANG_SUC_KHOE> TINH_TRANG_SUC_KHOE { get; set; }
        public DbSet<THU> THU { get; set; }
    }
}
