//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHA_CUNG_CAP
    {
        public NHA_CUNG_CAP()
        {
            this.CHI_PHI_DOI_TUONG = new HashSet<CHI_PHI_DOI_TUONG>();
            this.CHI_PHI_THUC_PHAN = new HashSet<CHI_PHI_THUC_PHAN>();
        }
    
        public string IDNCC { get; set; }
        public string TENNCC { get; set; }
        public string TENSPCUNGCAP { get; set; }
        public string DIACHI { get; set; }
        public string SDT { get; set; }
    
        public virtual ICollection<CHI_PHI_DOI_TUONG> CHI_PHI_DOI_TUONG { get; set; }
        public virtual ICollection<CHI_PHI_THUC_PHAN> CHI_PHI_THUC_PHAN { get; set; }
    }
}
