//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManage
{
    using System;
    using System.Collections.Generic;
    
    public partial class THU
    {
        public int IDDOITUONG { get; set; }
        public string IDNHATIEUTHU { get; set; }
        public string IDSANPHAMTIEUTHU { get; set; }
        public string TENSANPHAMTIEUTHU { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<int> GIATHANH { get; set; }
    
        public virtual DOI_TUONG DOI_TUONG { get; set; }
        public virtual NGUON_TIEU_THU NGUON_TIEU_THU { get; set; }
    }
}
